name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - main
      - gh-pages
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Remove old storybook static files
        run: rm -rf storybook-static

      - name: Build Storybook
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm install
          npm run build-storybook

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          destination_dir: ${{ github.ref_name }} 
